BEGIN TRANSACTION;
DROP TABLE IF EXISTS "USERGROUPS";
CREATE TABLE "USERGROUPS" (
	"GID"	INTEGER NOT NULL UNIQUE,
	"NAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("GID" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "USERS";
CREATE TABLE "USERS" (
	"UID"	INTEGER NOT NULL UNIQUE,
	"USERNAME"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("UID" AUTOINCREMENT)
);

DROP TABLE IF EXISTS "USER_KEYS";
CREATE TABLE "USER_KEYS" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"KEY"	TEXT NOT NULL,
	"UID"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	CONSTRAINT "FK_UID" FOREIGN KEY("UID") REFERENCES "USERS"("UID") ON UPDATE RESTRICT ON DELETE CASCADE
);

DROP TABLE IF EXISTS "GROUP_MEMBERSHIP";
CREATE TABLE "GROUP_MEMBERSHIP" (
	"GID"	INTEGER NOT NULL,
	"UID"	INTEGER NOT NULL,
	PRIMARY KEY("GID","UID"),
	CONSTRAINT "FK_UID" FOREIGN KEY("UID") REFERENCES "USERS"("UID") ON DELETE CASCADE
	CONSTRAINT "FK_GID" FOREIGN KEY("GID") REFERENCES "USERGROUPS"("GID") ON DELETE RESTRICT,
);
DROP TABLE IF EXISTS "REPOS";
CREATE TABLE "REPOS" (
	"REPO"	TEXT NOT NULL,
	"UID"	INTEGER NOT NULL,
	"GID"   INTEGER,
	"UPERM"	TEXT NOT NULL DEFAULT "---",
	"GPERM"	TEXT NOT NULL DEFAULT "---",
	PRIMARY KEY("REPO"),
	CONSTRAINT "FK_UID" FOREIGN KEY("UID") REFERENCES "USERS"("UID") ON DELETE CASCADE
	CONSTRAINT "FK_GID" FOREIGN KEY("GID") REFERENCES "USERGROUPS"("GID") ON DELETE RESTRICT
);



COMMIT;
